# Only [allowlist] is picked up by the LeakTK scanning service
[allowlist]
  description = "Repo Allowlist"
  paths = [
    # Ignore any path with ignore.d in it
    '''ignore\.d''',

    # Ignore all files ending in .ignore.txt
    '''\.ignore\.txt$''',

    # An example of a full path
    '''examples\/some\/long\/path\/server.key$''',

    # Ignore the .gitleaks.toml
    '''\.gitleaks\.toml$''',
  ]
  regexes = [
    # '''custom-regexes-to-ignore-here''',
  ]

# [[rules]] are not picked up by the LeakTK scanning service
[[rules]]
  description = "fake-leaks-custom-rule"
  regex = '''asdfasdfasdfasdf'''
  tags = ["fake-leaks-custom-rule"]
