[allowlist]
  description = "Allowlist"
  paths = [
    '''ignore\.d''',
  ]
  files = [
    '''\.ignore\.txt$''',
    '''^\.?gitleaks.toml$''',
  ]

[[rules]]
  description = "fake-leaks-custom-rule"
  regex = '''asdfasdfasdfasdf'''
  tags = ["fake-leaks-custom-rule"]
