---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phase-config
data:
  HOST: "localhost"
  HTTP_PROTOCOL: "http://" # Need to change to https after TLS
  SSO_PROVIDERS: "google,github,gitlab"
  DATABASE_HOST: "phase-postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgres-db-name"
  DATABASE_USER: "postgres-user"
  REDIS_HOST: "phase-redis"
  REDIS_PORT: "6379"
  NEXT_TELEMETRY_DISABLED: "1"

---
apiVersion: v1
stringData:
  DATABASE_PASSWORD: "a765b22179964c53c8a32acccf5dd90d5fc832607bdd14fccaaaa0062adfd"
  GOOGLE_CLIENT_ID:
kind: Secret
metadata:
  name: phase-secrets
type: Opaque
