---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mopidy
  labels:
    app: mopidy
# Basic auth to protect the ingress. Can use htpasswd to generate passwords
# > htpasswd -n -b testuser testpass
stringData:
  htpasswd: |-
    testuser:$apr1$JXRA7j2s$LpVns9vsme8FHN0r.aSt11
