objects:
- apiVersion: v1
  stringData:
    guest: "${WHISK_GUEST_AUTH}"
    system: "${WHISK_SYSTEM_AUTH}"
  kind: Secret
  metadata:
    name: whisk.auth
    annotations:
      template.openshift.io/expose-auth: "{.data['system']}"
- apiVersion: v1
  stringData:
    db_username: "${COUCHDB_USER}"
    db_password: "${COUCHDB_PASSWORD}"
    db_secret: "${COUCHDB_SECRET}"
  kind: Secret
  metadata:
    name: db.auth
