manifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${local.username}-${project.name}-camo-secret
      # TODO: annotations/labels
    type: Opaque
    stringData:
      # these are documented in the README.md
      CAMO_KEY: ${var.CAMO_KEY }
