apiVersion: external-secrets.io/v1beta1
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  refreshInterval: 1h
  target:
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: my-secrets-manager-secret
metadata:
  name: api-key
  namespace: my-namespace
kind: ExternalSecret
