apiVersion: 'kubernetes-client.io/v1'
metadata:
  name: actions-exporter
  namespace: github-actions-exporter
spec:
  backendType: secretsManager
  data:
    - key: MySecretManagerKey
      name: github_token
      property: github_token
kind: ExternalSecret
