# https://github.com/cloudify-cosmo/cloudify-kubernetes-plugin/blob/6b92ea403ad9ef56b93551bcbcadfcf869a79677/v2_plugin.yaml#L265
cloudify.kubernetes.types.SecretDefinition:
  derived_from: cloudify.kubernetes.types.AbstractResource
  description: >
    Secret holds secret data of a certain type.
    The total bytes of the values in the Data field must be less than MaxSecretSize bytes
  properties:
    type:
      description: >
        Used to facilitate programmatic handling of secret data.
      type: string
      required: false
    data:
      description: >
        Data contains the secret data.
      default: {}
    stringData:
      description: >
        stringData allows specifying non-binary secret data in string form.
        It is provided as a write-only convenience method.
        All keys and values are merged into the data field on write,
        overwriting any existing values. It is never output when reading from the API..
      default: {}
